#!/bin/sh

# Author: Zhang Huangbin (michaelbibby <at> gmail.com)

export AMAVISD_SERVER='127.0.0.1'
export AMAVISD_CONF='/etc/amavisd.conf'
export AMAVISD_LOGFILE='/var/log/amavisd.log'
export AMAVISD_LOGROTATE_FILE="${LOG_ROTATE_DIR}/amavisd"
export AMAVISD_DKIM_DIR='/var/lib/dkim'
export AMAVISD_DKIM_SELECTOR='dkim'

# Syslog setting, 'YES' or 'NO'
export AMAVISD_SEPERATE_LOG='NO'
