#!/bin/sh

# Author: Zhang Huangbin (michaelbibby <at> gmail.com)

export POSTFIXADMIN_VERSION='2.2.1.1'
export POSTFIXADMIN_TARBALL="postfixadmin-${POSTFIXADMIN_VERSION}.tar.gz"
export POSTFIXADMIN_HTTPD_ROOT="${HTTPD_SERVERROOT}/postfixadmin-${POSTFIXADMIN_VERSION}"
