#!/usr/bin/env bash

# Author: Zhang Huangbin <michaelbibby (at) gmail.com>

#---------------------------------------------------------------------
# This file is part of iRedMail, which is an open source mail server
# solution for Red Hat(R) Enterprise Linux, CentOS, Debian and Ubuntu.
#
# iRedMail is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# iRedMail is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with iRedMail.  If not, see <http://www.gnu.org/licenses/>.
#---------------------------------------------------------------------

# -------------------------------------------------------
# ---------------------- ejabberd -----------------------
# -------------------------------------------------------

ejabberd_config()
{
    ECHO_INFO "==================== ejabberd ===================="

    # Add first domain as virtual host.
    perl -pi -e 's#^{hosts,.*##g' ${EJABBERD_CONF}
    cat >> ${EJABBERD_CONF} <<EOF
${CONF_MSG}
# Virtual domains.
{hosts, ["${FIRST_DOMAIN}"}.

# Authenticate against LDAP.
{auth_method, ldap}.
{ldap_servers, ["${LDAP_SERVER_HOST}"]}.
%%% {ldap_encrypt, tls}.
{ldap_port, ${LDAP_SERVER_PORT}}.
{ldap_rootdn, "${LDAP_BINDDN}"}.
{ldap_password, "${LDAP_BINDPW}"}.
{ldap_base, "${LDAP_BASEDN}"}.
{ldap_uids, [{"mail", "%u@%d"}]}.
{ldap_filter," (&(objectClass=${LDAP_OBJECTCLASS_MAILUSER})(${LDAP_ATTR_ACCOUNT_STATUS}=${LDAP_STATUS_ACTIVE})(${LDAP_ENABLED_SERVICE}=jabber))"}.
EOF

    echo 'export status_ejabberd_config="DONE"' >> ${STATUS_FILE}
}
