#!/bin/sh

# Author: Zhang Huangbin (michaelbibby <at> gmail.com)

# Awstats homepage: http://awstats.sf.net/

# Variables for awstats and related.

export AWSTATS_CONF_DIR='/etc/awstats'
export AWSTATS_HTTPD_CONF="${HTTPD_CONF_DIR}/awstats.conf"

# Used for apache directory access list. Generated via 'htpasswd' command.
export AWSTATS_HTPASSWD_FILE="${HTTPD_CONF_DIR}/awstats.users"

export AWSTATS_CONF_SAMPLE="${AWSTATS_CONF_DIR}/awstats.localhost.localdomain.conf"
export AWSTATS_CONF_WEB="${AWSTATS_CONF_DIR}/awstats.${HOSTNAME}.conf"
export AWSTATS_CONF_MAIL="${AWSTATS_CONF_DIR}/awstats.mail.conf"
