#!/usr/bin/env bash

# Author:   Zhang Huangbin (michaelbibby <at> gmail.com)

#---------------------------------------------------------------------
# This file is part of iRedMail, which is an open source mail server
# solution for Red Hat(R) Enterprise Linux, CentOS, Debian and Ubuntu.
#
# iRedMail is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# iRedMail is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with iRedMail.  If not, see <http://www.gnu.org/licenses/>.
#---------------------------------------------------------------------

# Awstats homepage: http://awstats.sf.net/

# Variables for awstats and related.

export AWSTATS_CONF_DIR='/etc/awstats'
export AWSTATS_HTTPD_CONF="${HTTPD_CONF_DIR}/awstats.conf"

# Used for apache directory access list. Generated via 'htpasswd' command.
export AWSTATS_HTPASSWD_FILE="${HTTPD_CONF_DIR}/awstats.users"

# Config files.
if [ X"${DISTRO}" == X"RHEL" ]; then
    export AWSTATS_CONF_SAMPLE="${AWSTATS_CONF_DIR}/awstats.localhost.localdomain.conf"
    export AWSTATS_HTTPD_ROOT="${HTTPD_SERVERROOT}/awstats"
    export AWSTATS_CGI_DIR="${AWSTATS_HTTPD_ROOT}"
elif [ X"${DISTRO}" == X"UBUNTU" -o X"${DISTRO}" == X"DEBIAN" ]; then
    export AWSTATS_CONF_SAMPLE="${AWSTATS_CONF_DIR}/awstats.conf"
    export AWSTATS_HTTPD_ROOT="/usr/share/awstats"

    # This path will be changed in 'functions/awstats.sh'.
    export AWSTATS_CGI_DIR="/usr/lib/cgi-bin"
elif [ X"${DISTRO}" == X"FREEBSD" ]; then
    export AWSTATS_HTTPD_ROOT="${HTTPD_SERVERROOT}/awstats"
    export AWSTATS_CONF_SAMPLE="${AWSTATS_HTTPD_ROOT}/cgi-bin/awstats.model.conf"
    export AWSTATS_CONF_DIR="${AWSTATS_HTTPD_ROOT}/cgi-bin"
    export AWSTATS_CGI_DIR="${AWSTATS_CONF_DIR}"
else
    :
fi
export AWSTATS_CONF_WEB="${AWSTATS_CONF_DIR}/awstats.${HOSTNAME}.conf"
export AWSTATS_CONF_MAIL="${AWSTATS_CONF_DIR}/awstats.mail.conf"

# Default language.
#   English:        en
#   Simp Chinese:   cn
#   Trad Chinese:   tw
export AWSTATS_LANGUAGE="en"
