#!/usr/bin/env bash

# Author: Zhang Huangbin (michaelbibby <at> gmail.com)

# ----------------------------------------
# For Dovecot and dovecot-sieve. 
# ----------------------------------------

if [ X"${DISTRO}" == X"RHEL" ]; then
    export DOVECOT_CONF='/etc/dovecot.conf'
    export DOVECOT_LDAP_CONF='/etc/dovecot-ldap.conf'
    export DOVECOT_MYSQL_CONF='/etc/dovecot-mysql.conf'
    export DOVECOT_DELIVER='/usr/libexec/dovecot/deliver'
elif [ X"${DISTRO}" == X"DEBIAN" -o X"${DISTRO}" == X"UBUNTU" ]; then
    export DOVECOT_CONF='/etc/dovecot/dovecot.conf'
    export DOVECOT_LDAP_CONF='/etc/dovecot/dovecot-ldap.conf'
    export DOVECOT_MYSQL_CONF='/etc/dovecot/dovecot-mysql.conf'
    export DOVECOT_DELIVER='/usr/lib/dovecot/deliver'
fi

# Dovecot user & group.
export DOVECOT_USER='dovecot'
export DOVECOT_GROUP='dovecot'

export DOVECOT_LOGROTATE_FILE="${LOGROTATE_DIR}/dovecot"
export SIEVE_LOGROTATE_FILE="${LOGROTATE_DIR}/sieve"

# Dovecot auth socket.
export DOVECOT_SOCKET_MUX='/var/spool/postfix/dovecot-auth'
export DOVECOT_SOCKET_MASTER='/var/run/dovecot/auth-master'

export DOVECOT_BIN='/usr/sbin/dovecot'
export DOVECOT_SIEVEC='/usr/libexec/dovecot/sievec'
export DOVECOT_LOG_FILE='/var/log/dovecot.log'

export SIEVE_LOG_FILE='/var/log/sieve.log'
# Do not starts with dot (.).
export SIEVE_RULE_FILENAME='dovecot.sieve'
export SIEVE_FILTER_FILE="${VMAIL_USER_HOME_DIR}/${SIEVE_RULE_FILENAME}"

# Dovecot plugin: Expire.
# NOTE: dict process currently runs as root, so this file will be owned as root.
export DOVECOT_EXPIRE_DICT_BDB='/var/lib/dovecot/expire/expire.db'

# Dovecot quota warning.
export DOVECOT_QUOTA_WARNING_BIN='/usr/bin/dovecot-quota-warning.sh'
