#!/bin/sh

# Author: Zhang Huangbin (michaelbibby <at> gmail.com)

# ----------------------------------------
# For Dovecot and dovecot-sieve. 
# ----------------------------------------

export DOVECOT_CONF='/etc/dovecot.conf'
export DOVECOT_LDAP_CONF='/etc/dovecot-ldap.conf'
export DOVECOT_MYSQL_CONF='/etc/dovecot-mysql.conf'

export DOVECOT_LOGROTATE_FILE="${LOG_ROTATE_DIR}/dovecot"

export DOVECOT_DELIVER='/usr/libexec/dovecot/deliver'
export DOVECOT_LOG_FILE='/var/log/dovecot.log'

export SIEVE_LOG_FILE='/var/log/sieve.log'
export SIEVE_RULE_FILENAME='.dovecot.sieve'
export SIEVE_FILTER_FILE="${VMAIL_USER_HOME_DIR}/${SIEVE_RULE_FILENAME}"
export SIEVE_DIR="${HTTPD_SERVERROOT}/sieve"
