#!/bin/bash

# Author: Zhang Huangbin (michaelbibby <at> gmail.com)

# Variables for Apache & PHP and related.

# ---- Apache ----

# Refer to files:
#   - functions/apache_php.sh
#   - functions/misc.sh
export HTTPD_PORT='80'

export HTTPD_SERVERROOT='/var/www'
export HTTPD_DOCUMENTROOT="${HTTPD_SERVERROOT}/html/"
export HTTPD_CONF="/etc/httpd/conf/httpd.conf"
export HTTPD_CONF_DIR="/etc/httpd/conf.d"
export PHP_MODULES_DIR="${HTTPD_SERVERROOT}/lib/php/modules/"
export HTTPD_SSL_CONF="${HTTPD_CONF_DIR}/ssl.conf"
export HTTPD_CERTS_DIR="/etc/httpd/certs"
export HTTPD_CERTS_PASSWD="$(${RANDOM_STRING})"

# ---- PHP ----
export PHP_INI='/etc/php.ini'
