#!/bin/bash

# Author: Zhang Huangbin (michaelbibby <at> gmail.com)

# Variables for Apache & PHP and related.

# ---- Apache ----

# Refer to files:
#   - functions/apache_php.sh
#   - functions/misc.sh
export HTTPD_PORT='80'

if [ X"${DISTRO}" == X"RHEL" ]; then
    export HTTPD_SERVERROOT='/var/www'
    export HTTPD_DOCUMENTROOT="${HTTPD_SERVERROOT}/html"
    export HTTPD_CONF="/etc/httpd/conf/httpd.conf"
    export HTTPD_CONF_DIR="/etc/httpd/conf.d"
    export HTTPD_SSL_CONF="${HTTPD_CONF_DIR}/ssl.conf"

    # ---- PHP ----
    export PHP_INI='/etc/php.ini'

elif [ X"${DISTRO}" == X"DEBIAN" ]; then
    export HTTPD_SERVERROOT='/usr/share/apache2'
    export HTTPD_DOCUMENTROOT="${HTTPD_SERVERROOT}/default-site"
    export HTTPD_CONF="/etc/apache2/apache2.conf"
    export HTTPD_CONF_DIR="/etc/apache2/conf.d"

    # ---- PHP ----
    export PHP_INI='/etc/php5/apache2/php.ini'

else
    :
fi
