#!/bin/sh

# Author: Zhang Huangbin (michaelbibby <at> gmail.com)

# Variables for MySQL database server and related.

export MYSQL_FRESH_INSTALLATION='YES'
export MYSQL_SERVER='127.0.0.1'
export MYSQL_PORT='3306'
export MYSQL_SOCKET='/var/lib/mysql/mysql.sock'
export MYSQL_ROOT_USER='root'

# MySQL config file.
export MYSQL_MY_CNF='/etc/my.cnf'

# For virtual user query in Postfix, Dovecot.
export MYSQL_BIND_USER="${VMAIL_USER_NAME}"
export MYSQL_BIND_PW="$(echo $RANDOM\$$RANDOM\@$RANDOM\!$RANDOM\&$RANDOM\*$RANDOM\)$RANDOM)"

# For vmail database management.
export MYSQL_ADMIN_USER="${VMAIL_ADMIN_USER_NAME}"

export MYSQL_INIT_SQL="${CONF_DIR}/mysql_init.sql"
export MYSQL_VMAIL_SQL="${CONF_DIR}/mysql_vmail.sql"

# MySQL database to store virtual hosts.
export VMAIL_DB='vmail'
export SAMPLE_SQL="${SAMPLE_DIR}/iredmail.sql"
