#!/bin/sh

# Author: Zhang Huangbin (michaelbibby <at> gmail.com)

export PHPMYADMIN_VERSION='2.11.9.4-all-languages'
export PHPMYADMIN_TARBALL="phpMyAdmin-${PHPMYADMIN_VERSION}.tar.bz2"
export PHPMYADMIN_HTTPD_ROOT="${HTTPD_SERVERROOT}/phpMyAdmin-${PHPMYADMIN_VERSION}"
export PHPMYADMIN_CONFIG_FILE="${PHPMYADMIN_HTTPD_ROOT}/config.inc.php"
