#!/usr/bin/env bash

# Author: Zhang Huangbin (michaelbibby <at> gmail.com)

#---------------------------------------------------------------------
# This file is part of iRedMail, which is an open source mail server
# solution for Red Hat(R) Enterprise Linux, CentOS, Debian and Ubuntu.
#
# iRedMail is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# iRedMail is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with iRedMail.  If not, see <http://www.gnu.org/licenses/>.
#---------------------------------------------------------------------

export POSTFIXADMIN_VERSION='2.2.1.1'
export POSTFIXADMIN_TARBALL="postfixadmin-${POSTFIXADMIN_VERSION}.tar.gz"
export POSTFIXADMIN_HTTPD_ROOT="${HTTPD_SERVERROOT}/postfixadmin-${POSTFIXADMIN_VERSION}"

# Use config.local.php to store settings, so that you get smooth upgrade.
export POSTFIXADMIN_CONF_LOCAL="${POSTFIXADMIN_HTTPD_ROOT}/config.local.php"

# Default Language.
export POSTFIXADMIN_DEFAULT_LANGUAGE='en'

# Site admin name and password.
export POSTFIXADMIN_ADMIN_NAME='admin'
export POSTFIXADMIN_ADMIN_PASSWD='admin'
