#!/bin/bash

# Author: Zhang Huangbin (michaelbibby <at> gmail.com)

export PROCMAIL_BIN='/usr/bin/procmail'
export PROCMAILRC='/etc/procmailrc'
export PROCMAIL_LOGFILE='/var/log/procmail.log'
export PROCMAIL_LOGROTATE_FILE="${LOGROTATE_DIR}/procmail"
