#!/usr/bin/env bash

# Author: Zhang Huangbin (michaelbibby <at> gmail.com)

# ---------------------------------------
# RoundcubeMail. http://roundcube.net
# ---------------------------------------
export RCM_VERSION='0.2.1'
export RCM_TARBALL="roundcubemail-${RCM_VERSION}.tar.gz"
export RCM_HTTPD_ROOT="${HTTPD_SERVERROOT}/roundcubemail-${RCM_VERSION}"

# Syslog log file.
export RCM_LOGFILE='/var/log/roundcube.log'
export RCM_LOGROTATE_FILE="${LOGROTATE_DIR}/roundcube"

# Database setting.
export RCM_DB="roundcubemail"
export RCM_DB_USER="roundcube"
export RCM_DB_PASSWD="$(${RANDOM_STRING})"
