#!/usr/bin/env bash

# Author:   Zhang Huangbin (michaelbibby <at> gmail.com)

#---------------------------------------------------------------------
# This file is part of iRedMail, which is an open source mail server
# solution for Red Hat(R) Enterprise Linux, CentOS, Debian and Ubuntu.
#
# iRedMail is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# iRedMail is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with iRedMail.  If not, see <http://www.gnu.org/licenses/>.
#---------------------------------------------------------------------

# ----------------------------------------
# For SquirrelMail. 
# ----------------------------------------

# Version number for core program: SquirrelMail.
export SM_VERSION='1.4.19'
export SM_TARBALL="squirrelmail-${SM_VERSION}.tar.bz2"

# ----------------------------------------
# For SquirrelMail plugins.
# ----------------------------------------

# These plugins will be enabled by default.
# The plugin name is the directory name you extract the source tarball.
# Warning: It should only include backend independ plugins.
export ENABLED_SM_PLUGINS="calendar compatibility check_quota autosubscribe email_footer login_auto select_language avelsieve add_address"

# change_ldappass
# URL: http://www.squirrelmail.org/plugin_view.php?id=26
export PLUGIN_CHANGE_LDAPPASS_TARBALL="change_ldappass-2.2-1.4.0.tar.gz"

# change_sqlpass
export PLUGIN_CHANGE_SQLPASS_TARBALL="change_sqlpass-3.3-1.2.tar.gz"

# Compatibiliry.
export PLUGIN_COMPATIBILITY_TARBALL='compatibility-2.0.14-1.0.tar.gz'

# Check Quota.
export PLUGIN_CHECK_QUOTA_TARBALL="check_quota-2.2-1.4.0.tar.gz"

# Select Language.
export PLUGIN_SELECT_LANGUAGE_TARBALL="select_language-1.1-1.4.0.tar.gz"

# AutoSubscribe.
export PLUGIN_AUTOSUBSCRIBE_TARBALL='autosubscribe-1.1-1.4.2.tar.gz'

# Email Footer.
export PLUGIN_EMAIL_FOOTER_TARBALL='email_footer-0.5-1.4.2.tar.gz'

# login_auto.
export PLUGIN_LOGIN_AUTO='login_auto-1.1-1.2.tar.gz'

# avelsieve.
export PLUGIN_AVELSIEVE='avelsieve-1.0.1.tar.gz'

# add_address.
export PLUGIN_ADD_ADDRESS='add_address-1.0.1-1.4.0.tar.gz'


# ----------------------------------------
# For SquirrelMail Translations.
# ----------------------------------------
export SM_TRANSLATIONS_TARBALL="all_locales-1.4.13-20071220.tar.gz"

# Default charset.
export SM_DEFAULT_CHARSET='utf-8'

#
# You do *NOT* need to modify the following args.
#
export SM_HTTPD_ROOT="${HTTPD_SERVERROOT}/squirrelmail-${SM_VERSION}"
export SM_CONF_PL="${SM_HTTPD_ROOT}/config/conf.pl"
export SM_CONFIG="${SM_HTTPD_ROOT}/config/config.php"
export SM_LOCAL_CONF="${SM_HTTPD_ROOT}/config/config_local.php"
export SM_PLUGIN_DIR="${SM_HTTPD_ROOT}/plugins/"

export PLUGIN_CHANGE_LDAPPASS_CONFIG="${SM_PLUGIN_DIR}/change_ldappass/config.php"
export PLUGIN_CHANGE_SQLPASS_CONFIG="${SM_PLUGIN_DIR}/change_sqlpass/config.php"
export SM_DATA_DIR="${SM_HTTPD_ROOT}/data/"
export SM_ATTACHMENT_DIR="${SM_HTTPD_ROOT}/attachments/"
